[book]
authors = ["Jurriën Arends"]
language = "en"
multilingual = false
src = "src"
title = "Assignment Process & Safety Jurriën Arends"

[preprocessor.plantuml]
plantuml-cmd="http://localhost:8181"

[output.html]
default-theme = "Rust"